### ISSUE TITLE
does django-markdown-app support django-1.11.4

### ISSUE THREAD

**Issue by BouchaaraAdil** [sv0/django-markdown-app#11]

**Comment by mcjon3z** [comment]
Appears that a [commit](https://github.com/sv0/django-markdown-app/commit/7c05c640451bd9e8b1c00d7293065e8944acbec3) to change requirements to allow 1.11 has been made in this repo however the pip package has not been updated since the previous [commit](https://github.com/sv0/django-markdown-app/commit/7bf5e94719772bd407c319c377d9c8cefe3db50b). Current pip package is 0.9.2...

You can install with the --no-deps option and it will not pick up the django <1.11 requirement, but you'll also have to install the markdown package separately via pip if you don't already have it installed...

**Comment by sv0** [comment]
I've uploaded ver 0.9.3 to pypi including @rspeed's fixes.

**Comment by rspeed** [comment]
Confirmed that this bug is fixed.

**Comment by BouchaaraAdil** [comment]
Thanks guys ✋
