### ISSUE TITLE
version 0.9.4 not compatible with Django < 2.0, previous versions un-published

### ISSUE THREAD

**Issue by chris48s** [sv0/django-markdown-app#16]
Hi. I've hit an issue with this project because the latest version 0.9.4 is not compatible with Django <= 2.0. The failure is

```
from django.urls import path
ImportError: cannot import name 'path'
```

I note in the requirements on PyPI, you now say version 0.9.4 requires "Django (<=2.1,>=2.0)". That's fine. Normally I would fix this by pinning to an older version until we are able to upgrade our application. However it also seems that you've also removed all previous version of `django-markdown-app` from PyPI (or at least they have been removed):

![screenshot at 2018-02-14 15 09 21](https://user-images.githubusercontent.com/6025893/36211672-d1e0ea5a-1199-11e8-950e-c0eabba1b2e3.png)

Removing old versions of a package is generally considered bad package maintenance practice as it is likely to break build/deployment script for users of your package who have pinned to the deleted versions.

I also had a look to see if I could submit a PR to add backward-compatiblity with older django versions (1.11 is still well inside its support window - many user won't be able to upgrade to 2.0 yet), but the code on `master` in this repo doesn't match what I downloaded from PyPI.

Key asks are:
1. Any word on what has happened here?
2. Would it be possible to re-publish a version which supports Django < 2.0 to PyPI?
3. How could someone help fix this?

**Comment by sv0** [comment]
Sorry guys, it is my fault.
Shit happened while I've been playing with bumpversion.
So I decided to delete package on https://pypi.org/ and then upload all versions again.
But as I found it's impossible to upload the same version twice even after package deletetion.

So version 0.9.3 is now available as 0.9.3.1 on https://pypi.org/

**Comment by chris48s** [comment]
Thanks for the quick response @sv0. I can confirm pinning to 0.9.3.1 has fixed for us.

I'm happy to close this issue as resolved, but I expect you might find some more users with a pinned dependency appear over the next few days. You might want to leave it open so others can see how to fix easily without raising a duplicate issue. I'll leave it with you.

**Comment by maciejstromich** [comment]
Hi, we were pinned to version 0.11.1 and it has also disappeared. Shuld we pin to 0.9.3.1 as well?

**Comment by sv0** [comment]
@maciejstromich yes, you should pin to 0.9.3.1 for Django <2.0, and to 0.9.4.1 for Django >=2.0

**Comment by cdvv7788** [comment]
Question. Is it too hard to have a single version that supports all the currently supported django versions?
What I mean is that according to: https://www.djangoproject.com/weblog/2015/jun/25/roadmap/ the only versions that should be relevant are the 1.11 and 2.0. 
There are 2 versions in here, 0.9.3.1, which works for django 1.8-1.11 and the 0.9.4.1 which works for django>2. If I want to use this package and support all live versions of django, this will be a problem with the current setup.
If you want to support older versions, that's ok, but currently this setup complicates things. I cannot use the latest version because it does not support django's LTS version (which is the recommended one to go for stable workflows).
I hope you can understand what I mean. If there is an easy solution to this, I would like to know about it.

**Comment by rjmoggach** [comment]
putting this here instead of opening a new issue:

`django-markdown-app 0.9.4.1 has requirement Django<=2.1,>=2.0, but you'll have django 2.1.1 which is incompatible.`

**Comment by ehossack** [comment]
Thought I had a dependency issues with django 1.11, but looks like 0.9.3.1 has minimal differences over incrementals since 8.5 and works for us!
